project_id = "eeidevcyxpnorbgcskdf"

[functions.create-homologation]
verify_jwt = true

[functions.fetch-segsale-products]
verify_jwt = false

[functions.get-homologation-data]
verify_jwt = false

[functions.receive-vehicle]
verify_jwt = false

[functions.segsale-webhook]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false